### ISSUE TITLE
Configure email settings

### ISSUE THREAD

**Issue by jessicana** [prashants/webzash#157]
How can I configure the mail settings using FTP?

**Comment by prashants** [comment]
You mean you want to change mail settings directly from a file and upload
that using FTP ?

If that's the case then you can change mail settings from MySQL / Sqlite
database since settings are stored in the database not in file.

**Comment by jessicana** [comment]
Yes, I am trying to configure my mailserver settings using the database because I am unable to access the system. I locked myself out :)

**Comment by jessicana** [comment]
I think this is really relevant to this problem. If a user can configure their email server credentials, they can reset their password and restore their account. I appreciate a hint please.

**Comment by prashants** [comment]
pls check the original ticket where you had issues with admin password. You
were doing it correctly to the point of MySQL query (hope you are using
version 3.x).

You should not be using the MD5() method on the password string. Just paste
the entire string as it is since cakephp uses its own seed for the hashing
function and MD5() will not work.

This is what you should do doing :-

update wzusers set password = "this is where the password string goes
without any changes" where ID = 1;

**Comment by jessicana** [comment]
Solved. Thanks!

I had to add an admin user through the database. I will post the steps here for others to enrich the documentation.

Again, thank you very much for your support.
