### ISSUE TITLE
Upgrade CakePHP 

### ISSUE THREAD

**Issue by chacha** [prashants/webzash#41]
CakePHP 2.5.6 is about a year old now, with the current version being 3.1. It might be time to consider upgrading to the new version as they've done some major reconstruction on things like file structure and whatknot.

I noticed this because as I started to get setup to be able to contribute, I couldn't just clone the master branch of CakePHP and work with the latest and greatest.

**Comment by prashants** [comment]
There are few reason for not going after the latest version :

- For us 3.1 is still too early since we have just shifted to cakephp a year back. Also there is no extra benefit by shifting to 3.x. It works pretty well and there are no issues with 2.6.

- CakePHP 3.0.0 was released just 9 months back. We will wait till it gets stable enough with good documentations. Maybe after a year we might consider shifting to 3.x series.

**Comment by pjp-comp** [comment]
Hey@prashant,
Can we upgrade now to cakephp3.x ? if so does webzash support to latest one?
