### ISSUE TITLE
I cannot select any "Ledger" for entries.

### ISSUE THREAD

**Issue by frenchy5** [prashants/webzash#52]
I cannot make any entries.
To be more specific, i cannot select any "Ledger".
I can only select "please select.."

Can you help me out!

**Comment by chacha** [comment]
A couple things of note:

1) You needed to have added ledgers to the Chart of Accounts in order to  make entries. The default groups are just that, groups. Not ledgers.
2) Depending upon the entry type, you are limited on whether you can select Cash/Non-Cash accounts. I would test the Journal entry first and foremost because it doesn't have these limitations.

**Comment by frenchy5** [comment]
Thank you, that was it! Nice.
It was a quick response
